name = "GCodeCraft"
uuid = "3ac2bd3a-f5a9-48d9-9c58-04dece2359e3"
authors = ["Hugo Levy-Falk <hugo@klafyvel.me> and contributors"]
version = "1.0.0-DEV"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"

[extensions]
LibSerialPortExt = "LibSerialPort"

[compat]
Aqua = "0.6"
LibSerialPort = "0.5.2"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
